// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW36lOUqLU1gpnmioNVr6LUt93h_RFLLo',
    appId: '1:221408294088:web:7794563e41d734783021fd',
    messagingSenderId: '221408294088',
    projectId: 'crackers-world',
    authDomain: 'crackers-world.firebaseapp.com',
    storageBucket: 'crackers-world.firebasestorage.app',
    measurementId: 'G-SE50DCL7JP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtjbKybgpVIRiD02HbfPIHhwYppSU9Lpg',
    appId: '1:221408294088:android:1473013f1ed44f943021fd',
    messagingSenderId: '221408294088',
    projectId: 'crackers-world',
    storageBucket: 'crackers-world.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuctrrwX2NAgOkK7dHl2XWmobZyfGXX1w',
    appId: '1:221408294088:ios:bb560f84ae0dbd5f3021fd',
    messagingSenderId: '221408294088',
    projectId: 'crackers-world',
    storageBucket: 'crackers-world.firebasestorage.app',
    iosBundleId: 'com.crackersworld.android',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuctrrwX2NAgOkK7dHl2XWmobZyfGXX1w',
    appId: '1:221408294088:ios:bb560f84ae0dbd5f3021fd',
    messagingSenderId: '221408294088',
    projectId: 'crackers-world',
    storageBucket: 'crackers-world.firebasestorage.app',
    iosBundleId: 'com.crackersworld.android',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW36lOUqLU1gpnmioNVr6LUt93h_RFLLo',
    appId: '1:221408294088:web:5ecec69811146d543021fd',
    messagingSenderId: '221408294088',
    projectId: 'crackers-world',
    authDomain: 'crackers-world.firebaseapp.com',
    storageBucket: 'crackers-world.firebasestorage.app',
    measurementId: 'G-G3K126JJ5M',
  );
}
